name: Update Things and Deploy

on:
  push:
    branches: ['main']
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          persist-credentials: false
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install Dependencies
      run: |
        cd scripts
        pip install -r requirements.txt
    - name: Get Latest
      run: |
        python scripts/download.py
    - name: Build Site
      run: |
        npm ci
        npm run build
    - name: Upload Artifacts 🔺
      uses: actions/upload-artifact@v4
      with:
          name: dist
          path: dist
  deploy:
    name: Deploy Site
    needs: [build] # The second job must depend on the first one to complete before running, and uses ubuntu-latest instead of windows.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download Artifacts 🔻 # The built project is downloaded into the 'site' folder.
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Display Files
        run: ls -R dist/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            branch: deploy
            folder: dist
